ZH_CN_Patch = {
    "ui_close_old": "检测到旧版本[%s]正在运行, 是否关闭旧版本？",
    "ui_tm_title": "过热关机",
    "ui_tm_shutdown_temp": "自动关机温度",
    "ui_tm_ohm_exe_path": "OpenHardwareMonitor.exe位置",
    "ui_tm_ohm_json_url": "OpenHardwareMonitor-Json接口",
    "ui_tm_ohm_status_off": "OHM状态：关闭",
    "ui_tm_ohm_status_on": "OHM状态：开启",
    "ui_tm_ohm_launching": "尝试启动OHM中...",
    "ui_tm_ohm_launching_fail": "OHM启动失败 [%s]",
    "ui_tm_ohm_launching_fail_no_url": "OHM启动失败，请设置OHM.exe位置",
    "ui_tm_ohm_retrieving_json": "获取OHM资料中...",
    "ui_tm_ohm_retrieving_json_fail": "OHM服务器功能未开启或端口错误 %s",
    "ui_tm_current_cpu_status": "%s 温度[%s] 负载[%s] 电功耗[%s]",
    "ui_tm_current_gpu_status": "%s 温度[%s] 负载[%s] 风扇[%s] 电功耗[%s]   ",
    "ui_tm_current_shutdown_status": "关机温度墙:%s/%s 已触发关机次数:%s 上次过热关机时间:%s",
    "ui_bkup_title": "自动备份-[%s]",
    "ui_bkup_bk_setting": "备份设置",
    "ui_bkup_comp_setting": "压缩设置",
    "ui_bkup_delete_setting": "自动删除设置",
    "ui_bkup_src": "源目录",
    "ui_bkup_dest": "备份存储目录",
    "ui_bkup_feq": "备份间隔时间(秒)",
    "ui_bkup_enable_compress": "启用压缩",
    "ui_bkup_hour_limit": "本小时数量上限",
    "ui_bkup_day_limit": "本日数量上限",
    "ui_bkup_week_limit": "本周数量上限",
    "ui_bkup_month_limit": "本月数量上限",
    "ui_bkup_year_limit": "本年数量上限",
    "ui_bkup_overall_limit": "历史存档数量上限",
    "ui_bkup_keep_newest": "保留最新备份",
    "ui_bkup_keep_oldest": "保留最旧备份",
    "ui_bkup_keep_average": "保留时间平均备份",
    "ui_bkup_next_bkup": "下一次备份: %s/%s秒",
    "ui_bkup_thread_started": "备份线程状态: 正在运行",
    "ui_bkup_thread_stopped": "备份线程状态: 停止",
    "ui_launch_title": "%s启动器",
    "ui_launch_settings": "启动设置",
    "ui_launch_thread_status": "线程状态",
    "ui_launch_target": "启动目标",
    "ui_launch_params": "启动参数",
    "ui_launch_cwd": "工作路径CWD",
    "ui_launch_env": "环境变量(字典形式)",
    "ui_launch_restart_interval": "重启间隔（秒）",
    "ui_launch_pipe": "使用子控制台 NKLaunch.run_pipe()",
    "ui_launch_autorun": "自动运行",
    "ui_launch_proc_names": "重启时关闭进程名(逗号分隔):",
    "ui_launch_thread_started": "监控线程状态: 正在运行",
    "ui_launch_thread_stopped": "监控线程状态: 停止",
    "ui_pkup_title": "子目录打包器(自动重建根目录)-[%s]",
    "ui_pkup_root_setting_area": "选择根目录(可拖放)",
    "ui_pkup_subdir_setting_area": "选择子目录(批量选择并拖放)",
    "ui_pkup_src_root": "打包源-根目录",
    "ui_pkup_dest_dir": "打包至-根目录",
    "ui_pkup_start": "开始打包",
    "ui_pkup_pause": "暂停打包",
    "ui_pkup_restart": "重新开始",
    "ui_pkup_copy_selected": "打包选中的子目录",
    "ui_pkup_copy_unselected": "打包反选的子目录",
    "ui_pkup_hide_cmd": "隐藏CMD",
    "ui_butler_title": "自动化任务-[%s]",
    "ui_butler_timed": "定时",
    "ui_butler_countdown": "倒数",
    "ui_butler_tasklist_area": "任务列表 (点击以查看详情或手动运行)",
    "ui_butler_task_exec_history_area": "任务执行历史",
    "ui_butler_task_exec_logs_area": "任务日志-[%s]",
    "ui_butler_thread_status_area": "线程池状态",
    "ui_butler_follow_task": "父级任务:",
    "ui_butler_btn_run_selected_task": "运行选中任务",
    "ui_butler_btn_run_all_task": "运行所有任务",
    "ui_butler_btn_pause_all_task": "全体暂停",
    "ui_butler_btn_resume_all_task": "全体继续",
    "ui_butler_btn_clear_all_threads": "线程清理",
    "ui_butler_log_dir": "日志文件目录",
    "ui_butler_btn_apply_log_dir": "应用目录",
    "STATUS_REST": "休息中",
    "STATUS_QUEUED": "队列中",
    "STATUS_RUNNING": "运行中",
    "STATUS_COMPLETED": "已完成",
    "STATUS_NOT_EXIST": "不存在",
}
