ZH_CN_Patch = {
    "ui_tm_title": "过热关机",
    "ui_tm_shutdown_temp": "自动关机温度",
    "ui_tm_ohm_exe_path": "OpenHardwareMonitor.exe位置",
    "ui_tm_ohm_json_url": "OpenHardwareMonitor-Json接口",
    "ui_tm_ohm_status_off": "OHM状态：关闭",
    "ui_tm_ohm_status_on": "OHM状态：开启",
    "ui_tm_ohm_launching": "尝试启动OHM中...",
    "ui_tm_ohm_launching_fail": "OHM启动失败 [%s]",
    "ui_tm_ohm_launching_fail_no_url": "OHM启动失败，请设置OHM.exe位置",
    "ui_tm_ohm_retrieving_json": "获取OHM资料中...",
    "ui_tm_ohm_retrieving_json_fail": "OHM服务器功能未开启或端口错误 %s",
    "ui_tm_current_cpu_status": "%s 温度[%s] 负载[%s] 电功耗[%s]",
    "ui_tm_current_gpu_status": "%s 温度[%s] 负载[%s] 风扇[%s] 电功耗[%s]   ",
    "ui_tm_current_shutdown_status": "关机温度墙:%s/%s 已触发关机次数:%s 上次过热关机时间:%s",
    "ui_bkup_title": "自动备份-[%s]",
    "ui_bkup_bk_setting": "备份设置",
    "ui_bkup_comp_setting": "压缩设置",
    "ui_bkup_delete_setting": "自动删除设置",
    "ui_bkup_src": "源目录",
    "ui_bkup_dest": "备份存储目录",
    "ui_bkup_feq": "备份间隔时间(秒)",
    "ui_bkup_enable_compress": "启用压缩",
    "ui_bkup_hour_limit": "本小时数量上限",
    "ui_bkup_day_limit": "本日数量上限",
    "ui_bkup_week_limit": "本周数量上限",
    "ui_bkup_month_limit": "本月数量上限",
    "ui_bkup_year_limit": "本年数量上限",
    "ui_bkup_overall_limit": "历史存档数量上限",
    "ui_bkup_keep_newest": "保留最新备份",
    "ui_bkup_keep_oldest": "保留最旧备份",
    "ui_bkup_keep_average": "保留时间平均备份",
    "ui_bkup_next_bkup": "下一次备份: %s/%s秒",
    "ui_bkup_thread_started": "备份线程状态: 正在运行",
    "ui_bkup_thread_stopped": "备份线程状态: 停止",
}
