ZH_CN = {
    "lp_shots_management": "镜头号管理",
    "lp_get_shots_from_dir": "从文件夹获取镜头号",
    "lp_shot_dir": "镜头文件夹:",
    "lp_cs": "镜头号比对",
    "lp_cs_base_data": "场次镜头基础数据:",
    "lp_cs_target_data": "目标场次数据：",
    "lp_cs_result": "比对结果",
    "lp_cs_no_match": "未发现本场次基础数据",
    "lp_cs_compared": "比对完成",
    "lp_cs_compare_only_one": "只能对比一场，请勿复制多场",
    "lp_ap": "资产打包",
    "lp_ap_net_drv_help": "必须映射X盘，否则解析贴图路径错.\n"
                          "subst X: /D\n"
                          "subst X: F:\XDrive\n"
                          "net use X: \\\\VitaliyServer\XDrive /user:username password",
    "lp_ap_control_panel": "控制面板",
    "lp_ap_pack_panel": "打包面板",
    "lp_ap_net_drv_root_dir": "选择资产盘符(X:\\)",
    "lp_ap_select_project": "选择打包项目",
    "lp_ap_refresh_projects": "刷新项目",
    "lp_ap_refresh_assets": "刷新资产",
    "lp_ap_select_asset_character": "选择要打包的角色",
    "lp_ap_select_asset_env": "选择要打包的场景",
    "lp_ap_select_asset_prop": "选择要打包的道具",
    "lp_ap_high_model": "打包高模",
    "lp_ap_low_model": "打包低模",
    "lp_ap_7z_command": "7Z命令",
    "lp_ap_7z_prepare": "分析并生成命令",
    "lp_ap_7z_run": "执行",
}
